apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-urqp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-urqp
    app.kubernetes.io/part-of: tkrw-pr712-0075-0018-app
  name: devfile-sample-urqp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-urqp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-urqp
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-urqp@sha256:9d1545736ddcf7bbd345c8bf7cfe244068da43c72c65c44f119c7a666220e4f5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
